### ISSUE TITLE
`[&OsStr; 7]` is not an iterator

### ISSUE THREAD

**Issue by jose1711** [Farmadupe/ffmpeg_cmdline_utils#2] opened 2022-01-24 23:46 UTC
Getting the following trying to build:
```
error[E0277]: `[&OsStr; 7]` is not an iterator
   --> /home/jose/.cargo/registry/src/github.com-1ecc6299db9ec823/ffmpeg_cmdline_utils-0.1.0/src/ffmpeg_ops.rs:134:21
    |
134 |           args.extend([
    |  _____________________^
135 | |             OsStr::new("-pix_fmt"),  OsStr::new("rgb24"),
136 | |             OsStr::new("-c:v"),      OsStr::new("rawvideo"),
137 | |             OsStr::new("-f"),        OsStr::new("image2pipe"),
138 | |             OsStr::new("-")
139 | |         ]);
    | |_________^ expected an implementor of trait `IntoIterator`
    |
    = note: the trait bound `[&OsStr; 7]: IntoIterator` is not satisfied
    = note: required because of the requirements on the impl of `IntoIterator` for `[&OsStr; 7]`
help: consider borrowing here
    |
134 |         args.extend(&[
135 |             OsStr::new("-pix_fmt"),  OsStr::new("rgb24"),
136 |             OsStr::new("-c:v"),      OsStr::new("rawvideo"),
137 |             OsStr::new("-f"),        OsStr::new("image2pipe"),
138 |             OsStr::new("-")
139 |         ]);
    |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `ffmpeg_cmdline_utils`

```

**Comment by Farmadupe** [comment] 2022-02-01 18:51
Hello, apologies for the late reply,

I guess that this is probably caused by trying to compile the code using a compiler older than version 1.53. Arrays did not implement IntoIterator until that version of rust. See https://doc.rust-lang.org/edition-guide/rust-2021/IntoIterator-for-arrays.html for more information.

I will probably not fix this issue, but if you are able to update your rust compiler then this problem will probably go away.

**Comment by Farmadupe** [comment] 2022-02-06 12:38
I have fixed this issue as part of the updates made in support of Czkawka in issue #1.

Fixed in github main branch.
Fixed in crates.io at v0.1.1

**Closed as completed by Farmadupe** 2022-02-06 12:38 UTC
